/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Warehouses */
        get: operations["get_warehouses_warehouses_get"];
        put?: never;
        /** Post Warehouse */
        post: operations["post_warehouse_warehouses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Locations */
        get: operations["get_locations_locations_get"];
        put?: never;
        /** Post Location */
        post: operations["post_location_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Products */
        get: operations["get_products_products_get"];
        put?: never;
        /** Post Product */
        post: operations["post_product_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Product */
        patch: operations["patch_product_products__product_id__patch"];
        trace?: never;
    };
    "/quants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quants */
        get: operations["get_quants_quants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operations */
        get: operations["get_operations_operations_get"];
        put?: never;
        /** Post Operation */
        post: operations["post_operation_operations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{op_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation Detail */
        get: operations["get_operation_detail_operations__op_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{op_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Transition */
        post: operations["post_transition_operations__op_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Moves */
        get: operations["get_moves_moves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ledger */
        get: operations["get_ledger_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Public warmup ping: the frontend calls this on load so Neon is awake before the user logs in.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DashboardOut */
        DashboardOut: {
            /** Products In Stock */
            products_in_stock: number;
            /** Low Stock */
            low_stock: number;
            /** Out Of Stock */
            out_of_stock: number;
            receipts: components["schemas"]["OpCounts"];
            deliveries: components["schemas"]["OpCounts"];
            transfers: components["schemas"]["OpCounts"];
            /** Alerts */
            alerts: components["schemas"]["StockAlert"][];
        };
        /** ForgotPasswordIn */
        ForgotPasswordIn: {
            /** Email */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LedgerOut */
        LedgerOut: {
            /** Id */
            id: number;
            /** Operation Id */
            operation_id: number;
            /** Product Id */
            product_id: number;
            /** Location Id */
            location_id: number;
            /** Delta */
            delta: number;
            /** Actor Id */
            actor_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LineIn */
        LineIn: {
            /** Product Id */
            product_id: number;
            /** Qty */
            qty: number | string;
        };
        /** LineOut */
        LineOut: {
            /** Product Id */
            product_id: number;
            /** Sku */
            sku: string;
            /** Product Name */
            product_name: string;
            /** Uom */
            uom: string;
            /** Qty */
            qty: number;
        };
        /** LocationIn */
        LocationIn: {
            /** Warehouse Id */
            warehouse_id: number;
            /** Name */
            name: string;
            /** Short Code */
            short_code: string;
        };
        /** LocationOut */
        LocationOut: {
            /** Id */
            id: number;
            /** Warehouse Id */
            warehouse_id: number;
            /** Name */
            name: string;
            /** Short Code */
            short_code: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Login Id */
            login_id: string;
            /** Password */
            password: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Message */
            message: string;
        };
        /**
         * MoveOut
         * @description One product line of an operation, flattened for Move History.
         */
        MoveOut: {
            /** Operation Id */
            operation_id: number;
            /** Reference */
            reference: string;
            /**
             * Type
             * @enum {string}
             */
            type: "receive" | "transfer" | "delivery" | "adjustment";
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "waiting" | "ready" | "done" | "canceled";
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /** Partner */
            partner: string | null;
            /** Product Id */
            product_id: number;
            /** Sku */
            sku: string;
            /** Product Name */
            product_name: string;
            /** Uom */
            uom: string;
            /** Qty */
            qty: number;
            /** From Location */
            from_location: string | null;
            /** To Location */
            to_location: string | null;
        };
        /** OpCounts */
        OpCounts: {
            /**
             * Open
             * @default 0
             */
            open: number;
            /**
             * Ready
             * @default 0
             */
            ready: number;
            /**
             * Waiting
             * @default 0
             */
            waiting: number;
            /**
             * Late
             * @default 0
             */
            late: number;
            /**
             * Upcoming
             * @default 0
             */
            upcoming: number;
        };
        /** OperationDetail */
        OperationDetail: {
            /** Id */
            id: number;
            /** Reference */
            reference: string;
            /**
             * Type
             * @enum {string}
             */
            type: "receive" | "transfer" | "delivery" | "adjustment";
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "waiting" | "ready" | "done" | "canceled";
            /** Lines */
            lines: components["schemas"]["LineOut"][];
            /** Source Location Id */
            source_location_id: number | null;
            /** Dest Location Id */
            dest_location_id: number | null;
            /** Warehouse Id */
            warehouse_id: number;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /** Partner */
            partner: string | null;
            /** Delivery Address */
            delivery_address: string | null;
            /** Note */
            note: string | null;
            /** Created By */
            created_by: number;
            /** Responsible */
            responsible: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Transitions */
            transitions: components["schemas"]["TransitionOut"][];
            /** Ledger */
            ledger: components["schemas"]["LedgerOut"][];
        };
        /** OperationIn */
        OperationIn: {
            /**
             * Type
             * @enum {string}
             */
            type: "receive" | "transfer" | "delivery" | "adjustment";
            /** Lines */
            lines: components["schemas"]["LineIn"][];
            /** Source Location Id */
            source_location_id?: number | null;
            /** Dest Location Id */
            dest_location_id?: number | null;
            /** Scheduled Date */
            scheduled_date?: string | null;
            /** Partner */
            partner?: string | null;
            /** Delivery Address */
            delivery_address?: string | null;
            /** Note */
            note?: string | null;
        };
        /** OperationOut */
        OperationOut: {
            /** Id */
            id: number;
            /** Reference */
            reference: string;
            /**
             * Type
             * @enum {string}
             */
            type: "receive" | "transfer" | "delivery" | "adjustment";
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "waiting" | "ready" | "done" | "canceled";
            /** Lines */
            lines: components["schemas"]["LineOut"][];
            /** Source Location Id */
            source_location_id: number | null;
            /** Dest Location Id */
            dest_location_id: number | null;
            /** Warehouse Id */
            warehouse_id: number;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /** Partner */
            partner: string | null;
            /** Delivery Address */
            delivery_address: string | null;
            /** Note */
            note: string | null;
            /** Created By */
            created_by: number;
            /** Responsible */
            responsible: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProductIn */
        ProductIn: {
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /**
             * Uom
             * @default Units
             */
            uom: string;
            /**
             * Min Qty
             * @default 0
             */
            min_qty: number | string;
            /**
             * Unit Cost
             * @default 0
             */
            unit_cost: number | string;
            /**
             * Initial Qty
             * @default 0
             */
            initial_qty: number | string;
            /** Initial Location Id */
            initial_location_id?: number | null;
        };
        /** ProductOut */
        ProductOut: {
            /** Id */
            id: number;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Uom */
            uom: string;
            /** Min Qty */
            min_qty: number;
            /** Unit Cost */
            unit_cost: number;
        };
        /** ProductPatch */
        ProductPatch: {
            /** Sku */
            sku?: string | null;
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Uom */
            uom?: string | null;
            /** Min Qty */
            min_qty?: number | string | null;
            /** Unit Cost */
            unit_cost?: number | string | null;
        };
        /** QuantOut */
        QuantOut: {
            /** Product Id */
            product_id: number;
            /** Sku */
            sku: string;
            /** Product Name */
            product_name: string;
            /** Category */
            category: string;
            /** Uom */
            uom: string;
            /** Location Id */
            location_id: number;
            /** Location Name */
            location_name: string;
            /** Warehouse Id */
            warehouse_id: number;
            /** Unit Cost */
            unit_cost: number;
            /** Qty */
            qty: number;
            /** Free Qty */
            free_qty: number;
        };
        /** ResetPasswordIn */
        ResetPasswordIn: {
            /** Email */
            email: string;
            /** Otp */
            otp: string;
            /** New Password */
            new_password: string;
        };
        /** SignupIn */
        SignupIn: {
            /** Login Id */
            login_id: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** StockAlert */
        StockAlert: {
            /** Product Id */
            product_id: number;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Uom */
            uom: string;
            /** On Hand */
            on_hand: number;
            /** Min Qty */
            min_qty: number;
        };
        /** TransitionIn */
        TransitionIn: {
            /**
             * From
             * @enum {string}
             */
            from: "draft" | "waiting" | "ready" | "done" | "canceled";
            /**
             * To
             * @enum {string}
             */
            to: "draft" | "waiting" | "ready" | "done" | "canceled";
        };
        /** TransitionOut */
        TransitionOut: {
            /** From Status */
            from_status: ("draft" | "waiting" | "ready" | "done" | "canceled") | null;
            /**
             * To Status
             * @enum {string}
             */
            to_status: "draft" | "waiting" | "ready" | "done" | "canceled";
            /** Actor Id */
            actor_id: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Login Id */
            login_id: string;
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "staff" | "manager";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarehouseIn */
        WarehouseIn: {
            /** Name */
            name: string;
            /** Short Code */
            short_code: string;
            /** Address */
            address?: string | null;
        };
        /** WarehouseOut */
        WarehouseOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Short Code */
            short_code: string;
            /** Address */
            address: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    forgot_password_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_warehouses_warehouses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOut"][];
                };
            };
        };
    };
    post_warehouse_warehouses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarehouseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_locations_locations_get: {
        parameters: {
            query?: {
                warehouse_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_location_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_dashboard_get: {
        parameters: {
            query?: {
                warehouse_id?: number | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_products_get: {
        parameters: {
            query?: {
                category?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_product_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_product_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quants_quants_get: {
        parameters: {
            query?: {
                warehouse_id?: number | null;
                product_id?: number | null;
                category?: string | null;
                location_id?: number | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operations_operations_get: {
        parameters: {
            query?: {
                type?: ("receive" | "transfer" | "delivery" | "adjustment") | null;
                status?: ("draft" | "waiting" | "ready" | "done" | "canceled") | null;
                warehouse_id?: number | null;
                category?: string | null;
                location_id?: number | null;
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_operation_operations_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operation_detail_operations__op_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                op_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_transition_operations__op_id__transition_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                op_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_moves_moves_get: {
        parameters: {
            query?: {
                type?: ("receive" | "transfer" | "delivery" | "adjustment") | null;
                status?: ("draft" | "waiting" | "ready" | "done" | "canceled") | null;
                warehouse_id?: number | null;
                location_id?: number | null;
                product_id?: number | null;
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ledger_ledger_get: {
        parameters: {
            query?: {
                product_id?: number | null;
                location_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
